//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalilAlHaj.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DalilAlHaj.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة للمفضلة.
        /// </summary>
        internal static string AddedToFavorites {
            get {
                return ResourceManager.GetString("AddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤍 أضف للمفضلة.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسب المذهب المالكي.
        /// </summary>
        internal static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دليل الحاج.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛰️ جبل عرفات.
        /// </summary>
        internal static string Arafat {
            get {
                return ResourceManager.GetString("Arafat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المهام.
        /// </summary>
        internal static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم التاسع - ركن الحج الأعظم.
        /// </summary>
        internal static string ChecklistItem10Desc {
            get {
                return ResourceManager.GetString("ChecklistItem10Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقوف بعرفة.
        /// </summary>
        internal static string ChecklistItem10Title {
            get {
                return ResourceManager.GetString("ChecklistItem10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد غروب يوم عرفة.
        /// </summary>
        internal static string ChecklistItem11Desc {
            get {
                return ResourceManager.GetString("ChecklistItem11Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيت بمزدلفة.
        /// </summary>
        internal static string ChecklistItem11Title {
            get {
                return ResourceManager.GetString("ChecklistItem11Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوم النحر.
        /// </summary>
        internal static string ChecklistItem12Desc {
            get {
                return ResourceManager.GetString("ChecklistItem12Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمي جمرة العقبة.
        /// </summary>
        internal static string ChecklistItem12Title {
            get {
                return ResourceManager.GetString("ChecklistItem12Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد رمي جمرة العقبة.
        /// </summary>
        internal static string ChecklistItem13Desc {
            get {
                return ResourceManager.GetString("ChecklistItem13Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلق أو التقصير.
        /// </summary>
        internal static string ChecklistItem13Title {
            get {
                return ResourceManager.GetString("ChecklistItem13Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ركن من أركان الحج.
        /// </summary>
        internal static string ChecklistItem14Desc {
            get {
                return ResourceManager.GetString("ChecklistItem14Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طواف الإفاضة.
        /// </summary>
        internal static string ChecklistItem14Title {
            get {
                return ResourceManager.GetString("ChecklistItem14Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيام 11 و 12 و 13.
        /// </summary>
        internal static string ChecklistItem15Desc {
            get {
                return ResourceManager.GetString("ChecklistItem15Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمي الجمرات أيام التشريق.
        /// </summary>
        internal static string ChecklistItem15Title {
            get {
                return ResourceManager.GetString("ChecklistItem15Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل مغادرة مكة.
        /// </summary>
        internal static string ChecklistItem16Desc {
            get {
                return ResourceManager.GetString("ChecklistItem16Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طواف الوداع.
        /// </summary>
        internal static string ChecklistItem16Title {
            get {
                return ResourceManager.GetString("ChecklistItem16Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دراسة أركان وواجبات الحج.
        /// </summary>
        internal static string ChecklistItem1Desc {
            get {
                return ResourceManager.GetString("ChecklistItem1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعلم أحكام الحج.
        /// </summary>
        internal static string ChecklistItem1Title {
            get {
                return ResourceManager.GetString("ChecklistItem1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوبة النصوح وقضاء الديون.
        /// </summary>
        internal static string ChecklistItem2Desc {
            get {
                return ResourceManager.GetString("ChecklistItem2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوبة والاستغفار.
        /// </summary>
        internal static string ChecklistItem2Title {
            get {
                return ResourceManager.GetString("ChecklistItem2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواز السفر والتأشيرة.
        /// </summary>
        internal static string ChecklistItem3Desc {
            get {
                return ResourceManager.GetString("ChecklistItem3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجهيز الوثائق.
        /// </summary>
        internal static string ChecklistItem3Title {
            get {
                return ResourceManager.GetString("ChecklistItem3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملابس الإحرام والأمتعة.
        /// </summary>
        internal static string ChecklistItem4Desc {
            get {
                return ResourceManager.GetString("ChecklistItem4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحضير الملابس.
        /// </summary>
        internal static string ChecklistItem4Title {
            get {
                return ResourceManager.GetString("ChecklistItem4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوية الضرورية ومستلزمات الرعاية.
        /// </summary>
        internal static string ChecklistItem5Desc {
            get {
                return ResourceManager.GetString("ChecklistItem5Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوية والإسعافات.
        /// </summary>
        internal static string ChecklistItem5Title {
            get {
                return ResourceManager.GetString("ChecklistItem5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاغتسال ولبس ثياب الإحرام.
        /// </summary>
        internal static string ChecklistItem6Desc {
            get {
                return ResourceManager.GetString("ChecklistItem6Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحرام من الميقات.
        /// </summary>
        internal static string ChecklistItem6Title {
            get {
                return ResourceManager.GetString("ChecklistItem6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طواف القدوم وصلاة ركعتين.
        /// </summary>
        internal static string ChecklistItem7Desc {
            get {
                return ResourceManager.GetString("ChecklistItem7Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول مكة والطواف.
        /// </summary>
        internal static string ChecklistItem7Title {
            get {
                return ResourceManager.GetString("ChecklistItem7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبعة أشواط.
        /// </summary>
        internal static string ChecklistItem8Desc {
            get {
                return ResourceManager.GetString("ChecklistItem8Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعي بين الصفا والمروة.
        /// </summary>
        internal static string ChecklistItem8Title {
            get {
                return ResourceManager.GetString("ChecklistItem8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم الثامن من ذي الحجة.
        /// </summary>
        internal static string ChecklistItem9Desc {
            get {
                return ResourceManager.GetString("ChecklistItem9Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوجه إلى منى.
        /// </summary>
        internal static string ChecklistItem9Title {
            get {
                return ResourceManager.GetString("ChecklistItem9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المهام.
        /// </summary>
        internal static string ChecklistTasks {
            get {
                return ResourceManager.GetString("ChecklistTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ قائمة مهام الحج.
        /// </summary>
        internal static string ChecklistTitle {
            get {
                return ResourceManager.GetString("ChecklistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اللغة.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الموضوع:.
        /// </summary>
        internal static string ChooseTopic {
            get {
                return ResourceManager.GetString("ChooseTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} من {1} مكتمل.
        /// </summary>
        internal static string CompletedOf {
            get {
                return ResourceManager.GetString("CompletedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى:.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما قدرناش ننسخو.
        /// </summary>
        internal static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © AbdeljalilElYasni 2025.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 انسخ النص.
        /// </summary>
        internal static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع الليلي.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المفضلة.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير حجم الخط إلى.
        /// </summary>
        internal static string FontChanged {
            get {
                return ResourceManager.GetString("FontChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا مثال على حجم الخط المختار.
        /// </summary>
        internal static string FontExample {
            get {
                return ResourceManager.GetString("FontExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبير.
        /// </summary>
        internal static string FontLarge {
            get {
                return ResourceManager.GetString("FontLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        internal static string FontMedium {
            get {
                return ResourceManager.GetString("FontMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الخط.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صغير.
        /// </summary>
        internal static string FontSmall {
            get {
                return ResourceManager.GetString("FontSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تطبيق: دليل الحاج.
        /// </summary>
        internal static string FromApp {
            get {
                return ResourceManager.GetString("FromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕋 الكعبة المشرفة.
        /// </summary>
        internal static string Kaaba {
            get {
                return ResourceManager.GetString("Kaaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔊 استمع للمحتوى.
        /// </summary>
        internal static string ListenToContent {
            get {
                return ResourceManager.GetString("ListenToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما قدرناش نحمّلو البيانات.
        /// </summary>
        internal static string LoadDataError {
            get {
                return ResourceManager.GetString("LoadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري التحميل....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخريطة.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار حسب المذهب المالكي.
        /// </summary>
        internal static string MapRoute {
            get {
                return ResourceManager.GetString("MapRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خريطة مكة المكرمة.
        /// </summary>
        internal static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏕️ منى.
        /// </summary>
        internal static string Mina {
            get {
                return ResourceManager.GetString("Mina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌙 مزدلفة.
        /// </summary>
        internal static string Muzdalifah {
            get {
                return ResourceManager.GetString("Muzdalifah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسناً.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏸️ إيقاف.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️ تشغيل.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإزالة من المفضلة.
        /// </summary>
        internal static string RemovedFromFavorites {
            get {
                return ResourceManager.GetString("RemovedFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️ المفضلة.
        /// </summary>
        internal static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إعادة تشغيل التطبيق لتطبيق اللغة الجديدة.
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة التشغيل مطلوبة.
        /// </summary>
        internal static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتائج: {0}.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚶 الصفا والمروة.
        /// </summary>
        internal static string SafaMarwa {
            get {
                return ResourceManager.GetString("SafaMarwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث هنا....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتب للبحث....
        /// </summary>
        internal static string SearchPrompt {
            get {
                return ResourceManager.GetString("SearchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث.
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📤 شارك.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما قدرناش نشاركو.
        /// </summary>
        internal static string ShareError {
            get {
                return ResourceManager.GetString("ShareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجح.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نسخ النص بنجاح.
        /// </summary>
        internal static string TextCopied {
            get {
                return ResourceManager.GetString("TextCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواضيع:.
        /// </summary>
        internal static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإصدار 1.0.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 موقعك.
        /// </summary>
        internal static string YourLocation {
            get {
                return ResourceManager.GetString("YourLocation", resourceCulture);
            }
        }
    }
}
